#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from pico.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "pico.y"

  /* Aqui, pode-se inserir qualquer codigo C necessario ah compilacao
   * final do parser. Sera copiado tal como esta no inicio do y.tab.c
   * gerado por Yacc.
   */
  #include <stdio.h>
  #include <stdlib.h>
  #include <string.h>
  #include "node.h"
  #include "symbol_table.h"
  #include "lista.h"

  #define UNDEFINED_SYMBOL_ERROR -21
  #define ARRAY_INDEXES_ERROR -35

  #define LIT 124
  #define DUPLA 125

   typedef struct 
   {
	int ndim;
	int c[100];
	int size_of_type;
	int lim_inf[100];
	int lim_sup[100];
   } t_array;
 
   typedef struct
   {
    struct node_tac* code;
    char* correct;
    char* wrong;
   } t_boolexp;

   typedef struct
   {
    struct node_tac* code;
   } t_exp;

   typedef struct
   {
    struct node_tac* code;	
    char* idf;
   } t_exp_ar;

  /* macro pra concatenar as partes em str*/
  #define CAT(str,B,C,D) strcat(strcat(strcpy(str, B), C), D)

  /*árvore de sintaxe abstrata*/
  Node* syntax_tree;
  int lineno=1;

  /*tabela de símbolos*/
  symbol_t* s_table;
  long desloc = 0;
  long desloc_tmp = 0;

  /*lista de instruções*/
  struct node_tac* l_inst = NULL;
  int proxima_inst = 0;

  /* cabeçalho de algumas funções auxiliares */
  char* createTmp();
  char* createLbl(); 
  char* substr(char* fonte, int pos_i, int pos_f);
  int size_of_type(int type);
  void insert_list_of_vars(Node* n, int var_type);
  void insert_list_of_arrays(Node* n, int var_type, t_array* a);
  char* processa_arg(char* s, int line);
  t_boolexp* create_expbool(struct node_tac* _code, char* _c, char* _w);
  void verify_bool_exp(Node* node, char* _true, char* _false);
  void op_bool(Node* node, char* _true, char* _false);


#line 76 "pico.y"
typedef union {
  char* cadeia;
  struct _node* no;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IDF	258
#define	INT	259
#define	DOUBLE	260
#define	REAL	261
#define	CHAR	262
#define	QUOTE	263
#define	DQUOTE	264
#define	LE	265
#define	GE	266
#define	EQ	267
#define	NE	268
#define	AND	269
#define	OR	270
#define	NOT	271
#define	IF	272
#define	THEN	273
#define	ELSE	274
#define	WHILE	275
#define	INT_LIT	276
#define	F_LIT	277
#define	END	278
#define	TRUE	279
#define	FALSE	280
#define	PRINTF	281
#define	FOR	282
#define	NEXT	283
#define	UNTIL	284
#define	REPEAT	285


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IDF;
static const int INT;
static const int DOUBLE;
static const int REAL;
static const int CHAR;
static const int QUOTE;
static const int DQUOTE;
static const int LE;
static const int GE;
static const int EQ;
static const int NE;
static const int AND;
static const int OR;
static const int NOT;
static const int IF;
static const int THEN;
static const int ELSE;
static const int WHILE;
static const int INT_LIT;
static const int F_LIT;
static const int END;
static const int TRUE;
static const int FALSE;
static const int PRINTF;
static const int FOR;
static const int NEXT;
static const int UNTIL;
static const int REPEAT;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IDF=258
	,INT=259
	,DOUBLE=260
	,REAL=261
	,CHAR=262
	,QUOTE=263
	,DQUOTE=264
	,LE=265
	,GE=266
	,EQ=267
	,NE=268
	,AND=269
	,OR=270
	,NOT=271
	,IF=272
	,THEN=273
	,ELSE=274
	,WHILE=275
	,INT_LIT=276
	,F_LIT=277
	,END=278
	,TRUE=279
	,FALSE=280
	,PRINTF=281
	,FOR=282
	,NEXT=283
	,UNTIL=284
	,REPEAT=285


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IDF=258;
const int YY_parse_CLASS::INT=259;
const int YY_parse_CLASS::DOUBLE=260;
const int YY_parse_CLASS::REAL=261;
const int YY_parse_CLASS::CHAR=262;
const int YY_parse_CLASS::QUOTE=263;
const int YY_parse_CLASS::DQUOTE=264;
const int YY_parse_CLASS::LE=265;
const int YY_parse_CLASS::GE=266;
const int YY_parse_CLASS::EQ=267;
const int YY_parse_CLASS::NE=268;
const int YY_parse_CLASS::AND=269;
const int YY_parse_CLASS::OR=270;
const int YY_parse_CLASS::NOT=271;
const int YY_parse_CLASS::IF=272;
const int YY_parse_CLASS::THEN=273;
const int YY_parse_CLASS::ELSE=274;
const int YY_parse_CLASS::WHILE=275;
const int YY_parse_CLASS::INT_LIT=276;
const int YY_parse_CLASS::F_LIT=277;
const int YY_parse_CLASS::END=278;
const int YY_parse_CLASS::TRUE=279;
const int YY_parse_CLASS::FALSE=280;
const int YY_parse_CLASS::PRINTF=281;
const int YY_parse_CLASS::FOR=282;
const int YY_parse_CLASS::NEXT=283;
const int YY_parse_CLASS::UNTIL=284;
const int YY_parse_CLASS::REPEAT=285;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		124
#define	YYFLAG		-32768
#define	YYNTBASE	47

#define YYTRANSLATE(x) ((unsigned)(x) <= 285 ? yytranslate[x] : 65)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    41,
    42,    34,    32,    38,    33,     2,    35,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    37,    36,    46,
    31,    45,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    39,     2,    40,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    43,     2,    44,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     5,     8,    12,    16,    18,    22,    24,    26,
    28,    30,    32,    34,    39,    44,    49,    54,    58,    64,
    67,    71,    75,    77,    79,    84,    86,    91,    93,    97,
   101,   105,   109,   113,   117,   119,   121,   123,   125,   130,
   132,   140,   148,   153,   155,   159,   161,   163,   167,   171,
   175,   178,   182,   186,   190,   194,   198
};

static const short yyrhs[] = {    48,
    55,     0,    55,     0,    49,    36,     0,    48,    49,    36,
     0,    50,    37,    51,     0,     3,     0,     3,    38,    50,
     0,    52,     0,    53,     0,     4,     0,     5,     0,     6,
     0,     7,     0,     4,    39,    54,    40,     0,     5,    39,
    54,    40,     0,     6,    39,    54,    40,     0,     7,    39,
    54,    40,     0,    21,    37,    21,     0,    21,    37,    21,
    38,    54,     0,    56,    36,     0,    56,    36,    55,     0,
    57,    31,    60,     0,    62,     0,     3,     0,     3,    39,
    59,    40,     0,     3,     0,     3,    39,    59,    40,     0,
    60,     0,    60,    38,    59,     0,    60,    32,    60,     0,
    60,    33,    60,     0,    60,    34,    60,     0,    60,    35,
    60,     0,    41,    60,    42,     0,    21,     0,    22,     0,
    58,     0,    61,     0,     3,    41,    59,    42,     0,    60,
     0,    17,    41,    64,    42,    18,    55,    63,     0,    20,
    41,    64,    42,    43,    55,    44,     0,    26,    41,    60,
    42,     0,    23,     0,    19,    55,    23,     0,    24,     0,
    25,     0,    41,    64,    42,     0,    64,    14,    64,     0,
    64,    15,    64,     0,    16,    64,     0,    60,    45,    60,
     0,    60,    46,    60,     0,    60,    10,    60,     0,    60,
    11,    60,     0,    60,    12,    60,     0,    60,    13,    60,
     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   142,   155,   166,   167,   176,   226,   228,   238,   239,   242,
   244,   246,   248,   252,   261,   270,   279,   290,   305,   318,
   319,   339,   370,   373,   381,   447,   456,   522,   525,   540,
   557,   574,   590,   606,   607,   612,   617,   618,   623,   633,
   634,   676,   687,   704,   706,   718,   721,   725,   734,   746,
   757,   768,   779,   790,   801,   812,   823
};

static const char * const yytname[] = {   "$","error","$illegal.","IDF","INT",
"DOUBLE","REAL","CHAR","QUOTE","DQUOTE","LE","GE","EQ","NE","AND","OR","NOT",
"IF","THEN","ELSE","WHILE","INT_LIT","F_LIT","END","TRUE","FALSE","PRINTF","FOR",
"NEXT","UNTIL","REPEAT","'='","'+'","'-'","'*'","'/'","';'","':'","','","'['",
"']'","'('","')'","'{'","'}'","'>'","'<'","code","declaracoes","declaracao",
"listadeclaracao","tipo","tipounico","tipolista","listadupla","acoes","comando",
"lvalue","rvalue","listaexpr","expr","chamaproc","enunciado","fiminstcontrole",
"expbool",""
};
#endif

static const short yyr1[] = {     0,
    47,    47,    48,    48,    49,    50,    50,    51,    51,    52,
    52,    52,    52,    53,    53,    53,    53,    54,    54,    55,
    55,    56,    56,    57,    57,    58,    58,    59,    59,    60,
    60,    60,    60,    60,    60,    60,    60,    60,    61,    62,
    62,    62,    62,    63,    63,    64,    64,    64,    64,    64,
    64,    64,    64,    64,    64,    64,    64
};

static const short yyr2[] = {     0,
     2,     1,     2,     3,     3,     1,     3,     1,     1,     1,
     1,     1,     1,     4,     4,     4,     4,     3,     5,     2,
     3,     3,     1,     1,     4,     1,     4,     1,     3,     3,
     3,     3,     3,     3,     1,     1,     1,     1,     4,     1,
     7,     7,     4,     1,     3,     1,     1,     3,     3,     3,
     2,     3,     3,     3,     3,     3,     3
};

static const short yydefact[] = {     0,
    26,     0,     0,    35,    36,     0,     0,     0,     0,     0,
     2,     0,     0,    37,    40,    38,    23,     0,     0,     0,
     0,     0,     0,    26,     0,     0,     1,     3,     0,    20,
     0,     0,     0,     0,     0,     6,     7,     0,    28,     0,
     0,    46,    47,     0,     0,     0,     0,     0,     0,    34,
     4,    10,    11,    12,    13,     5,     8,     9,    26,    21,
    22,    30,    31,    32,    33,    27,     0,    39,    51,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    43,     0,     0,     0,     0,     0,    29,    48,    54,
    55,    56,    57,    52,    53,    49,    50,     0,     0,    27,
     0,     0,     0,     0,     0,     0,     0,     0,    14,    15,
    16,    17,     0,    44,    41,    42,    18,     0,     0,    45,
    19,     0,     0,     0
};

static const short yydefgoto[] = {   122,
     8,     9,    10,    56,    57,    58,   102,    11,    12,    13,
    14,    38,    15,    16,    17,   115,    46
};

static const short yypact[] = {    34,
     3,   -21,   -18,-32768,-32768,    -5,    85,    34,    -3,    11,
-32768,    13,    26,-32768,   -23,-32768,-32768,    59,    85,    85,
    60,    60,    85,     6,    86,    41,-32768,-32768,   118,    76,
    85,    85,    85,    85,    85,    36,-32768,    43,   128,    44,
    60,-32768,-32768,    60,   102,     4,    38,   117,    85,-32768,
-32768,    39,    48,    55,    56,-32768,-32768,-32768,   114,-32768,
   -23,    -4,    -4,-32768,-32768,    58,    85,-32768,-32768,    98,
    50,    85,    85,    85,    85,    85,    85,    60,    60,    81,
    57,-32768,    63,    83,    83,    83,    83,-32768,-32768,   -23,
   -23,   -23,   -23,   -23,   -23,-32768,   113,    76,    76,-32768,
    79,    89,    99,   101,   106,   -15,    94,   121,-32768,-32768,
-32768,-32768,    76,-32768,-32768,-32768,   116,   133,    83,-32768,
-32768,   157,   158,-32768
};

static const short yypgoto[] = {-32768,
-32768,   156,   147,-32768,-32768,-32768,   -80,    -8,-32768,-32768,
-32768,   -17,    -6,-32768,-32768,-32768,   -20
};


#define	YYLAST		166


static const short yytable[] = {    27,
    25,    47,    40,   113,   103,   104,   105,   114,    32,    33,
    34,    35,    39,    39,    45,    45,    48,    78,    79,    21,
    69,    60,    22,    71,    61,    62,    63,    64,    65,    34,
    35,    83,    28,   -24,    45,    23,     1,    70,   121,    -6,
    18,    19,    39,    20,    49,    80,    20,    29,    30,    88,
     2,    78,    79,     3,     4,     5,    31,    96,    97,     6,
    39,    36,    24,    78,    79,    90,    91,    92,    93,    94,
    95,    45,    45,    18,     7,    41,    51,    84,    59,    81,
     4,     5,    66,    42,    43,    68,    85,    24,   -25,   106,
   107,    89,     2,    86,    87,     3,     4,     5,    98,    99,
    44,     6,   100,   101,   118,     4,     5,    72,    73,    74,
    75,    72,    73,    74,    75,   108,     7,    32,    33,    34,
    35,    52,    53,    54,    55,     7,    78,    50,   109,    32,
    33,    34,    35,    32,    33,    34,    35,   116,   110,    50,
   111,   117,    76,    77,   -24,   112,    76,    77,    32,    33,
    34,    35,    19,   119,    20,   120,   123,   124,    82,    32,
    33,    34,    35,    26,    37,    67
};

static const short yycheck[] = {     8,
     7,    22,    20,    19,    85,    86,    87,    23,    32,    33,
    34,    35,    19,    20,    21,    22,    23,    14,    15,    41,
    41,    30,    41,    44,    31,    32,    33,    34,    35,    34,
    35,    49,    36,    31,    41,    41,     3,    44,   119,    37,
    38,    39,    49,    41,    39,    42,    41,    37,    36,    67,
    17,    14,    15,    20,    21,    22,    31,    78,    79,    26,
    67,     3,     3,    14,    15,    72,    73,    74,    75,    76,
    77,    78,    79,    38,    41,    16,    36,    39,     3,    42,
    21,    22,    40,    24,    25,    42,    39,     3,    31,    98,
    99,    42,    17,    39,    39,    20,    21,    22,    18,    43,
    41,    26,    40,    21,   113,    21,    22,    10,    11,    12,
    13,    10,    11,    12,    13,    37,    41,    32,    33,    34,
    35,     4,     5,     6,     7,    41,    14,    42,    40,    32,
    33,    34,    35,    32,    33,    34,    35,    44,    40,    42,
    40,    21,    45,    46,    31,    40,    45,    46,    32,    33,
    34,    35,    39,    38,    41,    23,     0,     0,    42,    32,
    33,    34,    35,     8,    18,    38
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 142 "pico.y"
{
			Node** children; 
			Node* pf1 = yyvsp[-1]. no ;
 			Node* pf3 = yyvsp[0]. no ; 
			pack_nodes(&children, 0, pf1);
			pack_nodes(&children, 1, pf3);
			syntax_tree = create_node(lineno, program_node, "raiz", yyvsp[0]. no ->attribute, 2, children);
			cat_tac(&l_inst, &((t_exp*)(yyvsp[0]. no ->attribute))->code);
			 			
			/*printf("raiz %d \n", lineno);
			printf("------------------- verificando tabela de simbolos ----------------------\n");
			print_table(*s_table);*/
		;
    break;}
case 2:
#line 155 "pico.y"
{ 
			/*Node** children; 
			Node* pf1 = $1;
			pack_nodes(&children, 0, pf1);
			syntax_tree = create_node(lineno, program_node, "raiz", NULL, 2, children);*/
			syntax_tree = create_node(lineno, program_node, "raiz", yyvsp[0]. no ->attribute, 1, &yyvsp[0]. no );
			cat_tac(&l_inst, &((t_exp*)(yyvsp[0]. no ->attribute))->code);
			/*syntax_tree = $1;*/
		;
    break;}
case 3:
#line 166 "pico.y"
{yyval. no  = yyvsp[-1]. no ;;
    break;}
case 4:
#line 167 "pico.y"
{Node** children; 
			 		 Node* pf1 = yyvsp[-2]. no ;
 			 		 Node* pf3 = yyvsp[-1]. no ; 
			 		 pack_nodes(&children, 0, pf1);
			 		 pack_nodes(&children, 1, pf3);
		yyval. no  = create_node(lineno, decl_node, "declaracoes", NULL, 2, children);
		/*printf("declaracoes %d \n", lineno);*/;
    break;}
case 5:
#line 176 "pico.y"
{	Node** children; 
			 		Node* pf1 = yyvsp[-2]. no ;
 			 		Node* pf3 = yyvsp[0]. no ; 
			 		pack_nodes(&children, 0, pf1);
			 		pack_nodes(&children, 1, pf3);

					
					/* verifica se eh uma array */
					if (nb_of_children(yyvsp[0]. no )==0)	
						/* insere as variaveis na lista de simbolos */		
						insert_list_of_vars(yyvsp[-2]. no , yyvsp[0]. no ->type);  
					else{
						/* arrays */
						/* printf("Botou na ST\n"); */
						t_array* a = malloc(sizeof(t_array));

						int i = 0;
						Node* temp = child(yyvsp[0]. no ,2);
						while((int)temp->attribute == DUPLA){
							a->lim_inf[i] = atoi(child(temp,1)->lexeme);
							a->lim_sup[i] = atoi(child(temp,2)->lexeme);
							temp = child(temp,3);
							i++;
						}
						a->ndim = i+1;
						a->lim_inf[i] = atoi(child(temp,1)->lexeme);
						a->lim_sup[i] = atoi(child(temp,2)->lexeme);

						/* preenche o c */
						a->c[i] = 1;		
						while( i > 0 ) {
							i--;
							/* acumula o tamanho da array */
							a->c[i] = (a->lim_sup[i+1] - a->lim_inf[i+1]) * a->c[i+1]; 
							printf("%i : %d %d %d\n", i, a->lim_sup[i+1],a->lim_inf[i+1], a->c[i]); 	
						}
	
						//a->lim_inf[0] = atoi(child(child($3,2),1)->lexeme);
						//printf("limite inferior %s\n", child(child($3,2),1)->lexeme);
						//a->lim_sup[0] = atoi(child(child($3,2),2)->lexeme);
						//printf("limite superior %s\n", child(child($3,2),2)->lexeme);
						insert_list_of_arrays(yyvsp[-2]. no ,child(yyvsp[0]. no ,1)->type,a);
						/*printf("nodo da array: %s \n", child(child($3,2),1)->lexeme);*/
					}					
		
					yyval. no  = create_node(lineno, decl_node, "declaracao", NULL, 2, children);
					/*printf("declaracao %d \n", lineno);*/;
    break;}
case 6:
#line 226 "pico.y"
{	Node* n = create_leaf(lineno, idf_node, yyvsp[0]. cadeia , NULL);  
			yyval. no  = n;;
    break;}
case 7:
#line 228 "pico.y"
{ Node** children;
					  Node* pf1 = create_leaf(lineno, idf_node, yyvsp[-2]. cadeia , NULL); 
					  Node* pf3 = yyvsp[0]. no ; 
					  pack_nodes(&children, 0, pf1);
					  pack_nodes(&children, 1, pf3);
					  yyval. no  = create_node(lineno, decl_list_node, "lista", NULL, 2, children);
					  /*printf("lista declaracao %s , %s, %d \n", $1, $3->lexeme,lineno);*/
					;
    break;}
case 8:
#line 238 "pico.y"
{ yyval. no  = yyvsp[0]. no ; ;
    break;}
case 9:
#line 239 "pico.y"
{ yyval. no  = yyvsp[0]. no ; ;
    break;}
case 10:
#line 242 "pico.y"
{ Node* n = create_leaf(lineno, int_node, yyvsp[0]. cadeia , NULL); 
		 yyval. no  = n; ;
    break;}
case 11:
#line 244 "pico.y"
{ Node* n = create_leaf(lineno, double_node, yyvsp[0]. cadeia , NULL); 
		 yyval. no  = n; ;
    break;}
case 12:
#line 246 "pico.y"
{ Node* n = create_leaf(lineno, real_node, yyvsp[0]. cadeia , NULL); 
		 yyval. no  = n; ;
    break;}
case 13:
#line 248 "pico.y"
{ Node* n = create_leaf(lineno, char_node, yyvsp[0]. cadeia , NULL); 
		 yyval. no  = n; ;
    break;}
case 14:
#line 253 "pico.y"
{ Node** children;
		  Node* pf1 = create_leaf(lineno, int_node, yyvsp[-3]. cadeia , NULL); 
		  Node* pf3 = yyvsp[-1]. no ; 
		  pack_nodes(&children, 0, pf1);
		  pack_nodes(&children, 1, pf3);
		  yyval. no  = create_node(lineno, decl_list_node, "tipolista", NULL, 2, children);
		  /*printf("tipolista %s , %s, %d \n", $1, $3->lexeme, lineno);*/
		;
    break;}
case 15:
#line 262 "pico.y"
{ Node** children;
		  Node* pf1 = create_leaf(lineno, double_node, yyvsp[-3]. cadeia , NULL); 
		  Node* pf3 = yyvsp[-1]. no ; 
		  pack_nodes(&children, 0, pf1);
		  pack_nodes(&children, 1, pf3);
		  yyval. no  = create_node(lineno, decl_list_node, "tipolista", NULL, 2, children);
		  /*printf("tipolista %s , %s, %d \n", $1, $3->lexeme, lineno);*/
		;
    break;}
case 16:
#line 271 "pico.y"
{ Node** children;
		  Node* pf1 = create_leaf(lineno, real_node, yyvsp[-3]. cadeia , NULL); 
		  Node* pf3 = yyvsp[-1]. no ; 
		  pack_nodes(&children, 0, pf1);
		  pack_nodes(&children, 1, pf3);
		  yyval. no  = create_node(lineno, decl_list_node, "tipolista", NULL, 2, children);
		  /*printf("tipolista %s , %s, %d \n", $1, $3->lexeme, lineno);*/
		;
    break;}
case 17:
#line 280 "pico.y"
{ Node** children;
		  Node* pf1 = create_leaf(lineno, char_node, yyvsp[-3]. cadeia , NULL); 
		  Node* pf3 = yyvsp[-1]. no ; 
		  pack_nodes(&children, 0, pf1);
		  pack_nodes(&children, 1, pf3);
		  yyval. no  = create_node(lineno, decl_list_node, "tipolista", NULL, 2, children);
		  /*printf("tipolista %s , %s, %d \n", $1, $3->lexeme, lineno);*/
		;
    break;}
case 18:
#line 291 "pico.y"
{ 

		 /* if( atoi($1) > atoi($3) ){
			return (ARRAY_INDEXES_ERROR);
		  }*/

		  Node** children;
		  Node* pf1 = create_leaf(lineno, int_node, yyvsp[-2]. cadeia , NULL); 
		  Node* pf3 = create_leaf(lineno, int_node, yyvsp[0]. cadeia , NULL);
		  pack_nodes(&children, 0, pf1);
		  pack_nodes(&children, 1, pf3);
		  yyval. no  = create_node(lineno, decl_list_node, "listadupla", (void*)LIT, 2, children);
		  /*printf("listadupla %s , %s, %d \n", $1, $3, lineno);*/
		;
    break;}
case 19:
#line 306 "pico.y"
{ Node** children;
		  Node* pf1 = create_leaf(lineno, int_node, yyvsp[-4]. cadeia , NULL); 
		  Node* pf2 = create_leaf(lineno, int_node, yyvsp[-2]. cadeia , NULL);
		  Node* pf3 = yyvsp[0]. no ;
		  pack_nodes(&children, 0, pf1);
		  pack_nodes(&children, 1, pf2);
		  pack_nodes(&children, 2, pf3);
		  yyval. no  = create_node(lineno, decl_list_node, "listadupla", (void*)DUPLA, 3, children);
		  /*printf("listadupla %s , %s, %s, %d \n", $1, $3, $5->lexeme, lineno);*/
		;
    break;}
case 20:
#line 318 "pico.y"
{ yyval. no  = yyvsp[-1]. no ; ;
    break;}
case 21:
#line 320 "pico.y"
{ Node** children;
		  Node* pf1 = yyvsp[-2]. no ; 
		  Node* pf3 = yyvsp[0]. no ;
		  pack_nodes(&children, 0, pf1);
		  pack_nodes(&children, 1, pf3);

 		  t_exp* ex = malloc(sizeof(t_exp));
		  ex->code = NULL;
		  
		  cat_tac(&(ex->code), &((t_exp*)yyvsp[-2]. no ->attribute)->code);	
		  cat_tac(&(ex->code), &((t_exp*)yyvsp[0]. no ->attribute)->code);
		  //ex->code = inst;
		  //printf("testeeeeeeeeee %s \n", ex->code->inst->res);		
	
		  yyval. no  = create_node(lineno, decl_list_node, "acoes", (void*)ex, 2, children);
		  /*printf("acoes %s , %s, %d \n", $1->lexeme, $3->lexeme, lineno);*/
		;
    break;}
case 22:
#line 340 "pico.y"
{ 
		  printf("%s  aa\n", yyvsp[-2]. no ->lexeme);
		  struct node_tac *inst = NULL;
		  //printf("%p lala\n",$3->attribute);
		  if (yyvsp[-2]. no ->attribute != NULL){ 
			printf("%s cc\n", yyvsp[0]. no ->lexeme);
			cat_tac(&inst, &((t_exp_ar*)yyvsp[-2]. no ->attribute)->code);
			append_inst_tac(&inst, create_inst_tac(yyvsp[-2]. no ->lexeme, ((t_exp_ar*)yyvsp[-2]. no ->attribute)->idf, "(", yyvsp[0]. no ->lexeme));
		  }else{
		  	append_inst_tac(&inst, create_inst_tac(yyvsp[-2]. no ->lexeme, yyvsp[0]. no ->lexeme, "", ""));
			//printf("asçdlfaçsldfha\n");
			
		  }
		  printf("casacasa\n");
		
		  //printf("%p --------\n", ((t_exp*)$3->attribute)->code->next); 
		  printf("a\n");
		  //if ($3->attribute != NULL)
		  cat_tac(&((t_exp*)yyvsp[0]. no ->attribute)->code, &inst);
		  //else
		  printf("b\n");
		  Node** children;
		  Node* pf1 = yyvsp[-2]. no ; 
		  Node* pf3 = yyvsp[0]. no ;
		  pack_nodes(&children, 0, pf1);
		  pack_nodes(&children, 1, pf3);
		  
		  yyval. no  = create_node(lineno, decl_list_node, "comando", yyvsp[0]. no ->attribute, 2, children);
		  /*printf("acoes %s , %s, %d \n", $1->lexeme, $3->lexeme, lineno);*/
		;
    break;}
case 23:
#line 370 "pico.y"
{ yyval. no  = yyvsp[0]. no ; ;
    break;}
case 24:
#line 373 "pico.y"
{ 	Node* n = create_leaf(lineno, idf_node, yyvsp[0]. cadeia , NULL); 
		yyval. no  = n;
		/* erro de variavel nao declarada */
		if (lookup(*s_table,n->lexeme)==NULL){	
			printf("UNDEFINED SYMBOL. A variavel %s nao foi declarada.\n", n->lexeme);
			return (UNDEFINED_SYMBOL_ERROR);
		}		
	    ;
    break;}
case 25:
#line 382 "pico.y"
{ 	 
		  Node** children;
		  Node* pf1 = create_leaf(lineno, idf_node, yyvsp[-3]. cadeia , NULL); 
		  Node* pf3 = yyvsp[-1]. no ;

		  t_exp_ar* tb = malloc(sizeof(t_exp_ar));
		  tb->code = NULL;
		  tb->idf = yyvsp[-3]. cadeia ;	

		  /* erro de variavel não declarada */
		  if (lookup(*s_table,pf1->lexeme)==NULL){	
			printf("UNDEFINED SYMBOL. A variavel %s nao foi declarada.\n", pf1->lexeme);
			return (UNDEFINED_SYMBOL_ERROR);
		  }	
                  


		  t_array* array_info = (t_array*)(lookup(*s_table,yyvsp[-3]. cadeia )->extra);
		  char* tmp0 = createTmp();
		  Node* temp = yyvsp[-1]. no ;
		  int i = 0;

		  while(nb_of_children(temp)>1) {
			char* tmp1 = createTmp();
			char* tmp2 = ( i == 0 ) ? NULL : createTmp();
			char lim_lit[200], c_lit[200];
			sprintf(lim_lit, "%d", array_info->lim_inf[i]);
			sprintf(c_lit, "%d", array_info->c[i]);

			printf("%s\n", child(temp,1)->lexeme);
			append_inst_tac(&(tb->code), create_inst_tac(tmp1, child(temp,1)->lexeme, "SUB", lim_lit));
			if( i == 0) {
				append_inst_tac(&(tb->code), create_inst_tac(tmp0, tmp1, "MUL", c_lit));
			} else {
				append_inst_tac(&(tb->code), create_inst_tac(tmp2, tmp1, "MUL", c_lit));
				append_inst_tac(&(tb->code), create_inst_tac(tmp0, tmp0, "ADD", tmp2));
			}
			temp = child(temp,2);
			i++;
			if( i > array_info->ndim)
				printf("erro de dimensoes\n");
		  }
		 
		  char lim_lit[200], s_type[200];
		  sprintf(lim_lit, "%d", array_info->lim_inf[i]);
		  sprintf(s_type, "%d", array_info->size_of_type);
		   	
		  if( i > 0){
			  char* tmp1 = createTmp();
			  append_inst_tac(&(tb->code), create_inst_tac(tmp1, temp->lexeme, "SUB", lim_lit));
			  append_inst_tac(&(tb->code), create_inst_tac(tmp0, tmp0, "ADD", tmp1));
		  }else{
			  append_inst_tac(&(tb->code), create_inst_tac(tmp0, temp->lexeme, "SUB", lim_lit));
		  }
		  append_inst_tac(&(tb->code), create_inst_tac(tmp0, tmp0, "MUL", s_type));
		

		  pack_nodes(&children, 0, pf1);
		  pack_nodes(&children, 1, pf3);	
		  yyval. no  = create_node(lineno, idf_node, tmp0, (void*)tb, 2, children);
		

		;
    break;}
case 26:
#line 447 "pico.y"
{ 	t_exp* te = malloc(sizeof(t_exp));
				Node* n = create_leaf(lineno, idf_node, yyvsp[0]. cadeia , te); 
				yyval. no  = n;
		/* erro de variavel nao declarada */
		if (lookup(*s_table,n->lexeme)==NULL){	
			printf("UNDEFINED SYMBOL. A variavel %s nao foi declarada.\n", n->lexeme);
			return (UNDEFINED_SYMBOL_ERROR);
		}		
	    ;
    break;}
case 27:
#line 457 "pico.y"
{ Node** children;
		  Node* pf1 = create_leaf(lineno, idf_node, yyvsp[-3]. cadeia , NULL); 
		  Node* pf3 = yyvsp[-1]. no ;

		  t_exp_ar* tb = malloc(sizeof(t_exp_ar));
		  tb->code = NULL;
		  tb->idf = yyvsp[-3]. cadeia ;	

		  /* erro de variavel não declarada */
		  if (lookup(*s_table,pf1->lexeme)==NULL){	
			printf("UNDEFINED SYMBOL. A variavel %s nao foi declarada.\n", pf1->lexeme);
			return (UNDEFINED_SYMBOL_ERROR);
		  }	
                  struct node_tac *inst = NULL;


		  t_array* array_info = (t_array*)(lookup(*s_table,yyvsp[-3]. cadeia )->extra);
		  char* tmp0 = createTmp();
		  Node* temp = yyvsp[-1]. no ;
		  int i = 0;
		  while(nb_of_children(temp)>1) {
			char* tmp1 = createTmp();
			char* tmp2 = ( i == 0 ) ? NULL : createTmp();
			char lim_lit[200], c_lit[200];
			sprintf(lim_lit, "%d", array_info->lim_inf[i]);
			sprintf(c_lit, "%d", array_info->c[i]);

			printf("%s\n", child(temp,1)->lexeme);
			append_inst_tac(&(tb->code), create_inst_tac(tmp1, child(temp,1)->lexeme, "SUB", lim_lit));
			if( i == 0) {
				append_inst_tac(&(tb->code), create_inst_tac(tmp0, tmp1, "MUL", c_lit));
			} else {
				append_inst_tac(&(tb->code), create_inst_tac(tmp2, tmp1, "MUL", c_lit));
				append_inst_tac(&(tb->code), create_inst_tac(tmp0, tmp0, "ADD", tmp2));
			}
			temp = child(temp,2);
			i++;
			if( i > array_info->ndim){
				printf("INDEX ERROR. %s acessada incorretamente.\n", pf1->lexeme);
				return (UNDEFINED_SYMBOL_ERROR);
			}
		  }

		  char lim_lit[200], s_type[200];
		  sprintf(lim_lit, "%d", array_info->lim_inf[i]);
		  sprintf(s_type, "%d", array_info->size_of_type);

		  if( i > 0){
			  char* tmp1 = createTmp();
			  append_inst_tac(&(tb->code), create_inst_tac(tmp1, temp->lexeme, "SUB", lim_lit));
			  append_inst_tac(&(tb->code), create_inst_tac(tmp0, tmp0, "ADD", tmp1));
		  }else{
			  append_inst_tac(&(tb->code), create_inst_tac(tmp0, temp->lexeme, "SUB", lim_lit));
		  }
		  append_inst_tac(&(tb->code), create_inst_tac(tmp0, tmp0, "MUL", s_type));
		  append_inst_tac(&(tb->code), create_inst_tac(tmp0, yyvsp[-3]. cadeia , ")", tmp0));

		  pack_nodes(&children, 0, pf1);
		  pack_nodes(&children, 1, pf3);
		  yyval. no  = create_node(lineno, idf_node, tmp0, (void*)tb, 2, children);

		;
    break;}
case 28:
#line 522 "pico.y"
{ 
		  
                  yyval. no  = create_node(lineno, op_node, yyvsp[0]. no ->lexeme, yyvsp[0]. no ->attribute, 0, &yyvsp[0]. no );;
    break;}
case 29:
#line 526 "pico.y"
{ 
		  
		  Node** children;
		  Node* pf1 = yyvsp[-2]. no ; 
		  Node* pf3 = yyvsp[0]. no ;
		  pack_nodes(&children, 0, pf1);
		  pack_nodes(&children, 1, pf3);
		  yyval. no  = create_node(lineno, op_node, "listaexpr", yyvsp[-2]. no ->attribute, 2, children);
		  /*printf("listaexpr %s , %s, %d \n", $1->lexeme, $3->lexeme, lineno);*/
		;
    break;}
case 30:
#line 540 "pico.y"
{  char* str = calloc(strlen(yyvsp[-2]. no ->lexeme)+strlen(yyvsp[0]. no ->lexeme)+2, sizeof(char*));
			CAT(str,yyvsp[-2]. no ->lexeme,yyvsp[0]. no ->lexeme,"+");
			/*PRECISA VERIFICAR OS OPERANDO PARA VER SE SÃO INT OU FLOAT*/

			t_exp* ex = malloc(sizeof(t_exp));
			ex->code = NULL;			

			char* tmp = createTmp();
			append_inst_tac(&(ex->code), create_inst_tac(tmp, yyvsp[-2]. no ->lexeme, "ADD", yyvsp[0]. no ->lexeme));
			
			Node** children; 
			Node* pf1 = yyvsp[-2]. no ;
 			Node* pf3 = yyvsp[0]. no ; 
			pack_nodes(&children, 0, pf1);
			pack_nodes(&children, 1, pf3);
			yyval. no  = create_node(lineno, op_node, tmp, (void*)ex, 2, children);
			;
    break;}
case 31:
#line 557 "pico.y"
{ 	char* str = calloc(strlen(yyvsp[-2]. no ->lexeme)+strlen(yyvsp[0]. no ->lexeme)+2, sizeof(char*)); 
			CAT(str,yyvsp[-2]. no ->lexeme,yyvsp[0]. no ->lexeme,"-");

			
			t_exp* ex = malloc(sizeof(t_exp));
			ex->code = NULL;	

			char* tmp = createTmp();
			append_inst_tac(&(ex->code), create_inst_tac(tmp, yyvsp[-2]. no ->lexeme, "SUB", yyvsp[0]. no ->lexeme));

			Node** children; 
			Node* pf1 = yyvsp[-2]. no ;
 			Node* pf3 = yyvsp[0]. no ; 
			pack_nodes(&children, 0, pf1);
			pack_nodes(&children, 1, pf3);
			yyval. no  = create_node(lineno, op_node, tmp, (void*)ex, 2, children);
			;
    break;}
case 32:
#line 574 "pico.y"
{ 	char* str = calloc(strlen(yyvsp[-2]. no ->lexeme)+strlen(yyvsp[0]. no ->lexeme)+2, sizeof(char*)); 
			CAT(str,yyvsp[-2]. no ->lexeme,yyvsp[0]. no ->lexeme,"*");

			t_exp* ex = malloc(sizeof(t_exp));
			ex->code = NULL;

			char* tmp = createTmp();
			append_inst_tac(&(ex->code), create_inst_tac(tmp, yyvsp[-2]. no ->lexeme, "MUL", yyvsp[0]. no ->lexeme));

			Node** children; 
			Node* pf1 = yyvsp[-2]. no ;
 			Node* pf3 = yyvsp[0]. no ; 
			pack_nodes(&children, 0, pf1);
			pack_nodes(&children, 1, pf3);
			yyval. no  = create_node(lineno, op_node, tmp, (void*)ex, 2, children);
			;
    break;}
case 33:
#line 590 "pico.y"
{ 	char* str = calloc(strlen(yyvsp[-2]. no ->lexeme)+strlen(yyvsp[0]. no ->lexeme)+2, sizeof(char*)); 
			CAT(str,yyvsp[-2]. no ->lexeme,yyvsp[0]. no ->lexeme,"/");

			t_exp* ex = malloc(sizeof(t_exp));
			ex->code = NULL;

			char* tmp = createTmp();
			append_inst_tac(&(ex->code), create_inst_tac(tmp, yyvsp[-2]. no ->lexeme, "DIV", yyvsp[0]. no ->lexeme));

			Node** children; 
			Node* pf1 = yyvsp[-2]. no ;
 			Node* pf3 = yyvsp[0]. no ; 
			pack_nodes(&children, 0, pf1);
			pack_nodes(&children, 1, pf3);
			yyval. no  = create_node(lineno, op_node, tmp, (void*)ex, 2, children);
			;
    break;}
case 34:
#line 606 "pico.y"
{ 	yyval. no  = yyvsp[-1]. no ; ;
    break;}
case 35:
#line 607 "pico.y"
{ 	
			t_exp* ex = malloc(sizeof(t_exp));
			ex->code = NULL;	
			yyval. no  = create_leaf(lineno, int_node, yyvsp[0]. cadeia , (void*)ex);
		     ;
    break;}
case 36:
#line 612 "pico.y"
{ 	
			t_exp* ex = malloc(sizeof(t_exp));
			ex->code = NULL;
			yyval. no  = create_leaf(lineno, real_node, yyvsp[0]. cadeia , NULL);
		     ;
    break;}
case 37:
#line 617 "pico.y"
{  yyval. no  = yyvsp[0]. no ;;
    break;}
case 38:
#line 618 "pico.y"
{	yyval. no  = yyvsp[0]. no ;;
    break;}
case 39:
#line 624 "pico.y"
{Node** children; 
		 Node* pf1 = create_leaf(lineno, idf_node, yyvsp[-3]. cadeia , NULL);
 		 Node* pf3 = yyvsp[-1]. no ; 
		 pack_nodes(&children, 0, pf1);
		 pack_nodes(&children, 1, pf3);
		 yyval. no  = create_node(lineno, proc_node, "chamaproc", NULL, 2, children); 
		 /*printf("chamaproc %s, %s \n", $1, $3->lexeme);*/;
    break;}
case 40:
#line 633 "pico.y"
{ yyval. no  = yyvsp[0]. no ; /*printf("%s \n",$1->lexeme);*/;
    break;}
case 41:
#line 635 "pico.y"
{
		 t_exp* ex = malloc(sizeof(t_exp));
		 ex->code = NULL;
		
		 Node** children; 
		 Node* pf1 = create_leaf(lineno, if_node, yyvsp[-6]. cadeia , NULL);
 		 Node* pf2 = yyvsp[-4]. no ;
		 Node* pf3 = create_leaf(lineno, cond_node, yyvsp[-2]. cadeia , NULL); 
		 Node* pf4 = yyvsp[-1]. no ; 
		 Node* pf5 = yyvsp[0]. no ; 
		 pack_nodes(&children, 0, pf1);
		 pack_nodes(&children, 1, pf2);
		 pack_nodes(&children, 2, pf3);
		 pack_nodes(&children, 3, pf4);
		 pack_nodes(&children, 4, pf5);

		 t_boolexp* b =	(t_boolexp*)yyvsp[-4]. no ->attribute;
		 t_exp* f = (t_exp*)yyvsp[-1]. no ->attribute;

		 char* lb_true = createLbl();
		 char* lb_false = createLbl();
		 char* lb_final = createLbl();

		 verify_bool_exp(yyvsp[-4]. no , lb_true, lb_false);
					
		 cat_tac(&(ex->code), &(b->code));
		 /* label do then */
		 append_inst_tac(&(ex->code), create_inst_tac(lb_true, "", "LABEL", ""));
		 /* codigo do then */
		 cat_tac(&(ex->code), &(f->code)); 
		 /* goto Next */
		 append_inst_tac(&(ex->code), create_inst_tac("GOTO", "", "GOTO", lb_final));
                 /* label do else */										
		 append_inst_tac(&(ex->code), create_inst_tac(lb_false, "", "LABEL", ""));
		 /* código do else */
		
		 /* label Next */
		append_inst_tac(&(ex->code), create_inst_tac(lb_final, "", "LABEL", ""));	

		yyval. no  = create_node(lineno, cond_node, "enunciado", (void*)ex, 5, children); 
		 /*printf("enunciado %s, %s \n", $1, $5);*/;
    break;}
case 42:
#line 677 "pico.y"
{Node** children; 
		 Node* pf1 = create_leaf(lineno, while_node, yyvsp[-6]. cadeia , NULL);
 		 Node* pf2 = yyvsp[-4]. no ;
		 Node* pf3 = yyvsp[-1]. no ; 
		 pack_nodes(&children, 0, pf1);
		 pack_nodes(&children, 1, pf2);
		 pack_nodes(&children, 2, pf3);
		 cat_tac(&l_inst, &((t_boolexp*)(yyvsp[-4]. no ->attribute))->code);
		 yyval. no  = create_node(lineno, cond_node, "enunciado", NULL, 3, children); 
		 /*printf("enunciado %s, %s \n", $3->lexeme, $6->lexeme);*/;
    break;}
case 43:
#line 688 "pico.y"
{Node** children;
		 Node* pf1 = create_leaf(lineno, print_node, yyvsp[-3]. cadeia , NULL);
		 Node* pf2 = yyvsp[-1]. no ;
		 
		 t_exp* ex = malloc(sizeof(t_exp));
		 ex->code =NULL;

		 //struct node_tac *inst = NULL;
		 append_inst_tac(&(ex->code), create_inst_tac("PRINT", yyvsp[-1]. no ->lexeme, "_", ""));
		 //cat_tac(&l_inst, &inst);
		 pack_nodes(&children, 0, pf1);
		 pack_nodes(&children, 1, pf2);
		 yyval. no  = create_node(lineno, print_node, "enunciado", (void*)ex, 2, children);
		;
    break;}
case 44:
#line 704 "pico.y"
{ 	Node* n = create_leaf(lineno, if_node, yyvsp[0]. cadeia , NULL); 
		       	yyval. no  = n;;
    break;}
case 45:
#line 707 "pico.y"
{Node** children; 
		 Node* pf1 = create_leaf(lineno, if_node, yyvsp[-2]. cadeia , NULL);
 		 Node* pf2 = yyvsp[-1]. no ;
		 Node* pf3 = create_leaf(lineno, if_node, yyvsp[0]. cadeia , NULL);
		 pack_nodes(&children, 0, pf1);
		 pack_nodes(&children, 1, pf2);
		 pack_nodes(&children, 2, pf3);
		 yyval. no  = create_node(lineno, proc_node, "fiminstcontrole", NULL, 3, children); 
		 /*printf("fiminstcontrole %s, %s \n", $1, $3);*/;
    break;}
case 46:
#line 718 "pico.y"
{ 	
			t_boolexp* tb = malloc(sizeof(t_boolexp));	
			yyval. no  = create_leaf(lineno, true_node, "true", tb);;
    break;}
case 47:
#line 721 "pico.y"
{ 	
			t_boolexp* tb = malloc(sizeof(t_boolexp));			
		       	yyval. no  = create_leaf(lineno, false_node, "false", tb);;
    break;}
case 48:
#line 725 "pico.y"
{ //$$ = $2;
		     	 t_boolexp* tb = malloc(sizeof(t_boolexp));			
			 Node** children;
			 pack_nodes(&children,0,create_leaf(lineno, parent_node, "(", NULL));
			 pack_nodes(&children,1,yyvsp[-1]. no );
			 pack_nodes(&children,2,create_leaf(lineno, parent_node,")",NULL));
			 yyval. no  = create_node(lineno,cond_node,"()",tb,3,children);

			;
    break;}
case 49:
#line 735 "pico.y"
{ 
		  t_boolexp* tb = malloc(sizeof(t_boolexp));
		  Node** children;
		  Node* node_and = create_leaf(lineno, and_node, "&", NULL);
		  pack_nodes(&children, 0, yyvsp[-2]. no );
		  pack_nodes(&children, 1, node_and);
		  pack_nodes(&children, 2, yyvsp[0]. no );

		  yyval. no  = create_node(lineno, cond_node, "expbool", tb, 3, children);

		;
    break;}
case 50:
#line 747 "pico.y"
{ 
		  t_boolexp* tb = malloc(sizeof(t_boolexp));
		  Node** children;
		  Node* node_or = create_leaf(lineno, or_node, "|", NULL);	  
		  pack_nodes(&children, 0, yyvsp[-2]. no );
		  pack_nodes(&children, 1, node_or);
		  pack_nodes(&children, 2, yyvsp[0]. no );
	
		  yyval. no  = create_node(lineno, cond_node, "expbool", tb, 3, children);
		;
    break;}
case 51:
#line 758 "pico.y"
{ 
 		  t_boolexp* tb = malloc(sizeof(t_boolexp));
		  Node** children; 
		  Node* pf1 = create_leaf(lineno, not_node, "not", NULL);
		  pack_nodes(&children, 0, pf1);
		  pack_nodes(&children, 1, yyvsp[0]. no );
		  
		  yyval. no  = create_node(lineno, cond_node, "expbool", tb, 2, children);
		  /*printf("expbool %s , %s, %d \n", $1, $2->lexeme, lineno);*/
		;
    break;}
case 52:
#line 769 "pico.y"
{ t_boolexp *at = malloc(sizeof(t_boolexp));
		  Node** children;
		  Node* pf1 = yyvsp[-2]. no ; 
		  Node* pf3 = yyvsp[0]. no ;
		  pack_nodes(&children,0,yyvsp[-2]. no );
		  pack_nodes(&children,1,create_leaf(lineno, sup_node,">",NULL));
		  pack_nodes(&children,2,yyvsp[0]. no );
		  yyval. no  = create_node(lineno, cond_node, ">", at, 3, children);
		  /*printf("expbool %s , %s, %d \n", $1->lexeme, $3->lexeme, lineno);*/
		;
    break;}
case 53:
#line 780 "pico.y"
{ t_boolexp *at = malloc(sizeof(t_boolexp));
		  Node** children;
		  Node* pf1 = yyvsp[-2]. no ; 
		  Node* pf3 = yyvsp[0]. no ;
		  pack_nodes(&children,0,yyvsp[-2]. no );
		  pack_nodes(&children,1,create_leaf(lineno, inf_node,"<",NULL));
		  pack_nodes(&children,2,yyvsp[0]. no );
		  yyval. no  = create_node(lineno, cond_node, "<", at, 3, children);
		  /*printf("expbool %s , %s, %d \n", $1->lexeme, $3->lexeme, lineno);*/
		;
    break;}
case 54:
#line 791 "pico.y"
{ t_boolexp *at = malloc(sizeof(t_boolexp));
		  Node** children;
		  Node* pf1 = yyvsp[-2]. no ; 
		  Node* pf3 = yyvsp[0]. no ;
		  pack_nodes(&children,0,yyvsp[-2]. no );
		  pack_nodes(&children,1,create_leaf(lineno, inf_eq_node,"<=",NULL));
		  pack_nodes(&children,2,yyvsp[0]. no );
		  yyval. no  = create_node(lineno, cond_node, "<=", at, 3, children);
		  /*printf("expbool %s , %s, %d \n", $1->lexeme, $3->lexeme, lineno);*/
		;
    break;}
case 55:
#line 802 "pico.y"
{ t_boolexp *at = malloc(sizeof(t_boolexp));
		  Node** children;
		  Node* pf1 = yyvsp[-2]. no ; 
		  Node* pf3 = yyvsp[0]. no ;
		  pack_nodes(&children,0,yyvsp[-2]. no );
		  pack_nodes(&children,1,create_leaf(lineno, sup_eq_node,">=",NULL));
		  pack_nodes(&children,2,yyvsp[0]. no );
		  yyval. no  = create_node(lineno, cond_node, ">=", at, 3, children);
		  /*printf("expbool %s , %s, %d \n", $1->lexeme, $3->lexeme, lineno);*/
		;
    break;}
case 56:
#line 813 "pico.y"
{ t_boolexp *at = malloc(sizeof(t_boolexp));
		  Node** children;
		  Node* pf1 = yyvsp[-2]. no ; 
		  Node* pf3 = yyvsp[0]. no ;
		  pack_nodes(&children,0,yyvsp[-2]. no );
		  pack_nodes(&children,1,create_leaf(lineno, eq_node,"==",NULL));
		  pack_nodes(&children,2,yyvsp[0]. no );
		  yyval. no  = create_node(lineno, cond_node, "==", at, 3, children);
		  /*printf("expbool %s , %s, %d \n", $1->lexeme, $3->lexeme, lineno);*/
		;
    break;}
case 57:
#line 824 "pico.y"
{ t_boolexp *at = malloc(sizeof(t_boolexp));
		  Node** children;
		  Node* pf1 = yyvsp[-2]. no ; 
		  Node* pf3 = yyvsp[0]. no ;
		  pack_nodes(&children,0,yyvsp[-2]. no );
		  pack_nodes(&children,1,create_leaf(lineno, neq_node,"!=",NULL));
		  pack_nodes(&children,2,yyvsp[0]. no );
		  yyval. no  = create_node(lineno, cond_node, "!=", at, 3, children);
		  /*printf("expbool %s , %s, %d \n", $1->lexeme, $3->lexeme, lineno);*/
		;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 835 "pico.y"



t_boolexp* create_expbool(struct node_tac* _code, char* _c, char* _w)
{
	t_boolexp* tb = calloc(1, sizeof(t_boolexp));
	tb->code = _code;
	tb->correct = _c;
	tb->wrong = _w;

	return tb;
}




 /* A partir daqui, insere-se qlqer codigo C necessario.
  */

void op_bool(Node* node, char* _true, char* _false)
{
	t_boolexp* tb = node->attribute;
	char* new_lb = createLbl();

	switch (child(node,1)->type)
	{
		case not_node:{  //not			
			verify_bool_exp(child(node,2),_false,_true);
			t_boolexp* f = child(node,2)->attribute;
			tb->code = f->code;			
			return;}
		case parent_node:{ //( )
			verify_bool_exp(child(node,2),_true,_false);
			t_boolexp* f = child(node,2)->attribute;
			tb->code = f->code;
			return;}
	}

	switch(child(node,2)->type)
	{
		case and_node: {// nnd			
			verify_bool_exp(child(node,1),new_lb,_false);
			verify_bool_exp(child(node,3),_true,_false);					
			tb->code = NULL;
			t_boolexp* filho0 = child(node,1)->attribute;
			t_boolexp* filho2 = child(node,3)->attribute;	
			cat_tac(&tb->code, &filho0->code);					
			/* continua avaliando: true */
			append_inst_tac(&(tb->code), create_inst_tac(new_lb, "", "LABEL", ""));
			cat_tac(&tb->code,&filho2->code);
		        break;}
		case or_node: {  //or					
			verify_bool_exp(child(node,1),_true,new_lb);
			verify_bool_exp(child(node,3),_true,_false);
					
			tb->code = NULL;
			t_boolexp* filho0 = child(node,1)->attribute;
			t_boolexp* filho2 = child(node,3)->attribute;
					
			cat_tac(&tb->code,&filho0->code);				
			/* continua avaliando: false */
			append_inst_tac(&(tb->code), create_inst_tac(new_lb, "", "LABEL", ""));
			cat_tac(&tb->code,&filho2->code);
			break; }
		default: { 
			/*  < , > , <= , >= , == . != */
			/* B -> B1 op B2 */
			printf("--------> %s\n",node->lexeme);
			tb->code = NULL;
			t_exp* filho0 = child(node,1)->attribute;
			t_exp* filho2 = child(node,3)->attribute;
			printf("ahahhah\n");
			/* código do filho0 */
			printf("%p\n", filho0);
			cat_tac(&tb->code,&filho0->code);
                     printf("primeiro cat\n");		
			/* código do filho2 */
			cat_tac(&tb->code,&filho2->code);
			char* op = calloc(200,sizeof(char));
			//strcat(op, "(");
		  	strcat(op, processa_arg(child(node,1)->lexeme,-1));
			strcat(op, " ");
		  	strcat(op, child(node,2)->lexeme);
			strcat(op, " ");
		  	strcat(op, processa_arg(child(node,3)->lexeme,-1));
			//strcat(op, ")");
			
					
			/* código do IF .. THEN .. IF op goto label*/ 
			append_inst_tac(&(tb->code), create_inst_tac("IF",op,"IF",_true));
			/* GOTO _false*/
			append_inst_tac(&(tb->code), create_inst_tac("GOTO", "", "GOTO", _false));
			break;}
	}

	
}

void verify_bool_exp(Node* node, char* _true, char* _false)
{
	t_boolexp* tb = node->attribute;
	switch(node->type)
	{
		case cond_node:
			op_bool(node, _true, _false);
			break;
		case true_node:
			tb->code = NULL;
			append_inst_tac(&(tb->code), create_inst_tac("GOTO", "", "GOTO", _true));
			break;	
		case false_node:
			tb->code = NULL;
			append_inst_tac(&(tb->code), create_inst_tac("GOTO", "", "GOTO", _false));
			break;	
	}	
}


/*função que verifica se a extensão do arquivo é .pico
 *retorna 0 caso seja
 *ou retorna -1 caso os últimos caracteres do nome do arquivo não sejam .pico
 */



int validExtension(char* s){
  int length = strlen(s);
  if (length < 5) return -1;
  if ((s[length-1] == 'o')&&(s[length-2] == 'c')&&
      (s[length-3] == 'i')&&(s[length-4] == 'p')&&(s[length-5] == '.'))
  	return 0;
  else return -1;
}

/* o mesmo que a anterior, porém verifica a extensão .tac */
int validOutputExtension(char* s){
  int length = strlen(s);
  if (length < 4) return -1;
  if ((s[length-1] == 'c')&&(s[length-2] == 'a')&&
      (s[length-3] == 't')&&(s[length-4] == '.'))
  	return 0;
  else return -1;
}

static int tmpNumber = 0;
char* createTmp(){
	char* ret;
	int size = 5;
	if (tmpNumber > 9) size++;
	if (tmpNumber > 99) size++;
	ret = calloc(size , sizeof(char));
	sprintf(ret, "tmp%i", tmpNumber);
	tmpNumber++;
	return ret;
}

static int lblNumber = 0;
char* createLbl(){
	char* ret;
	int size = 5;
	if (lblNumber > 9) size++;
	if (lblNumber > 99) size++;
	ret = calloc(size , sizeof(char));
	sprintf(ret, "LABEL%i", lblNumber);
	lblNumber++;
	return ret;
}

/* corta um char nas nas dimensoes especificadas */
char* substr(char* fonte, int pos_i, int pos_f)
{	
	int i,j=0;
	char* sub = malloc((pos_f-pos_i+1)*sizeof(char));
	for (i = pos_i; i<= pos_f; i++)
		sub[j++] = fonte[i];	

	return sub;
}


char* processa_arg(char* s, int line){
	if (strlen(s)==0) return "";
	int n=0, size=1;
	char* rg,*sp = "(SP)",*rx = "(Rx)";
	char* end = calloc(50,sizeof(char));

	 

	//printf("----> %s\n",s);
	
	if ((strlen(s) >= 3) && (s[0]=='t'&&s[1]=='m'&&s[2]=='p')){    	
		size = 4;					/* pegar o tamanho do tipo do tmp */
		rg = rx;
		switch(strlen(s))
		{
		case 4: 					/* para tmp0 ate tmp999 */
			n = atoi(substr(s,3,3)); 
			break;
		case 5: 
			n = atoi(substr(s,3,4)); 
			break;
		case 6: 
			n = atoi(substr(s,3,5)); 
			break;
		}
	}
	else if ((strlen(s) >= 5) && (s[0]=='P'&&s[1]=='R'&&s[2]=='I'&&s[3]=='N'&&s[4]=='T'))
	{
		sprintf(end,"%03d: PRINT",line);
		return end;
	}
	else if ((strlen(s) >= 2) && (s[0]=='I'&&s[1]=='F'))
	{	
		sprintf(end,"%03d: IF",line);
		return end;
	}
	else if ((strlen(s) >= 4) && (s[0]=='G'&&s[1]=='O'&&s[2]=='T'&&s[3]=='O'))
	{
		sprintf(end,"%03d: GOTO",line);
		return end;
	}
	else
	{
		
		rg = sp;
		entry_t* a = lookup(*s_table, s);		/* pega o desloc de s */
		if (a!=NULL){
			//printf("ahhhhhhhhhhhhhhhhhhhhhhhhhhhh!!\n");
			//if (a->extra == NULL)	
				n = a->desloc;}
			//else				/* se for array entra aki */
			
		else return s;
	}

	if (line==-1)
		sprintf(end,"%03d%s",n*size,rg);
	else{	
		sprintf(end,"%03d: %03d%s",line,n*size,rg);
	}

	return end;
}

void print_tac_baixo_nivel(struct node_tac* t, symbol_t *s, char* filename){	
	struct node_tac* temp = t;
	struct node_tac* nova = NULL;
	int line=0;
	
	while(temp != NULL){ 	
		/*printf("tac: %s\n", temp->inst->res);*/	
		append_inst_tac(&nova, 
			create_inst_tac(processa_arg(temp->inst->res,line),processa_arg(temp->inst->arg1,-1),	temp->inst->op, processa_arg(temp->inst->arg2,-1)));
		temp = temp->next;	
		line++;	
	}
   	FILE* output = fopen(filename, "w");
	fprintf(output,"%ld\n",desloc);
	fprintf(output,"%d\n",tmpNumber*4);
   	print_tac(output, nova);
	printf("final da funcao\n");
}

 /* funcao recursiva que percorre os nodos e vai colocando as variaveis na
     tabela de simbolos */
void insert_list_of_vars(Node* n, int var_type)
{
	if (nb_of_children(n) == 0){
		/* cria e insere uma nova entrada na tabela */
		entry_t* var = malloc(sizeof(entry_t));	
		var->name = n->lexeme;
		var->type = var_type;	
		var->size = size_of_type(var_type);
		var->desloc = desloc;
		desloc += var->size;
		insert(s_table, var); 	
	}
	else {
		int i;
		for (i=1; i <= nb_of_children(n); i++)
			insert_list_of_vars(child(n,i), var_type);
	}
}

void insert_list_of_arrays(Node* n, int var_type, t_array* a)
{
	if (nb_of_children(n) == 0){
		/*printf( "variavel: %s \n", n->lexeme);*/
		/* cria e insere uma nova entrada na tabela */
		entry_t* var = malloc(sizeof(entry_t));	
		var->name = n->lexeme;
		var->type = var_type;	
		var->size = size_of_type(var_type)*(a->lim_sup[0] - a->lim_inf[0] +1) ;
		var->desloc = desloc;
		a->size_of_type=size_of_type(var_type);
		var->extra = a;
		desloc += var->size;
		insert(s_table, var); 	
	}
	else {
		int i;
		for (i=1; i <= nb_of_children(n); i++)
			insert_list_of_vars(child(n,i), var_type);
	} 

}

/* retorna o tamanho do tipo */
int size_of_type(int type)
{
	switch(type)
	{
	case int_node:
		return 4;
	case real_node:
		return 4;
	case char_node:
		return 1;
	case double_node:
		return 8;
	}
	return 0;
}

#define DEBUG \
	printf("%s:%s:%i \n", __FILE__, __FUNCTION__, __LINE__)

char* progname;
extern FILE* yyin;

int main(int argc, char* argv[]) 
{
   
   /*inicializa deslocamento para declaração de variáveis*/
   desloc = 0;

   /*inicializa tabela de símbolos*/
   s_table = malloc(sizeof(symbol_t));					
   init_table(s_table);

   if (argc != 4) {
     printf("uso: %s -o <output_file> <input_file>. Try again!\n", argv[0]);
     exit(-1);
   }

   if (validExtension(argv[argc-1]) != 0){
     printf("Invalid Extension, the input file must have .pico extension\n");
     exit(-1);
   }
   
   /* parse the arguments
    * put the output filename in filename
    */ 
   char* filename;
   int i;
   for (i = 0; i < argc; i++){
   	if (strcmp(argv[i], "-o") == 0){
	   if (validOutputExtension(argv[i+1]) !=0) {
		printf("Invalid output extension, the output file must have .tac extension\n");
		exit(-1);
	   }
	   strcpy( filename = calloc(strlen(argv[i+1])+1 , sizeof(char)) , argv[i+1]);
	   /*printf("%s \n", filename);*/ 
	}
   }
  
   yyin = fopen(argv[argc-1], "r");
   if (!yyin) {
     printf("Uso: %s -o <output_file> <input_file>. Could not find %s. Try again!\n", 
         argv[0], argv[argc-1]);
     exit(-1);
   }

   progname = argv[0];

   if (!yyparse()) 
      printf("OKAY.\n");
   else 
      printf("ERROR.\n");
	


   /*opens the output archive to write*/
   char* filename_alto_nivel= calloc((strlen(filename)+3), sizeof(char));
   sprintf(filename_alto_nivel, "%san", filename); 
   FILE* output = fopen(filename_alto_nivel, "w"); 
   print_tac_baixo_nivel(l_inst, s_table, filename);
   print_tac(output, l_inst);
   fclose(output);

   print_tree(syntax_tree);
   
   return(0);
}

void yyerror(char* s) {
  fprintf(stderr, "%s: %s", progname, s);
  fprintf(stderr, "line %d\n", lineno);
}
